name: CI (Entorno Dev)

on:
  workflow_call:
    inputs:
      target: 
        type: string 
        required: true
 

jobs:
  get_image:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Set Image Tag Action
        uses: ./.github/actions/get-image-tag
        id: get_tag
        with:
          target: ${{ inputs.target }}

  build_and_push:
    needs: get_image
    runs-on: ubuntu-latest
    environment: target
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/RalonsoS/publish-packages/app
          tags: type=sha
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/RalonsoS/publish-packages/app:${{ needs.get_image.outputs.tag }}
